---
"python scratch.py":
  env:
    - cheese
    - cheeseonehot
    - hallway
    - hallwayonehot
    - mit
    - mitonehot
    - cit
    - citonehot
  goal_selection_strategy:
    - future
    - final
  layer-size:
    - 64
    - 32
    - 16
  seed:
    [0, 1, 2, 3, 4]
...
