---
"python scratch.py":
  env:
    - cheese
    - cheeseonehot
    - hallway
    - hallwayonehot
    - mit
    - mitonehot
    - cit
    - citonehot
  goal-selection-strategy:
    - future
    - final
 # layer-size:
 #   - 64
 #   - 32
 #   - 16
  reward-density:
    - sparse
    - dense
  seed:
    [0,1,2,3,4]
...
