---
"python scratch.py":
  env:
    - cheese
    - cheeseonehot
    - hallway
    - hallwayonehot
    - mit
    - mitonehot
    - cit
    - citonehot
  goal-selection-strategy:
    - future
    - final
  reward-density:
    - sparse
    - dense
  step-cap:
    [10, 15, 20, 50, 100, np.inf]
  seed:
    [0,1,2,3,4]
...
