#!/usr/bin/expect

set dir_list {cheese_final_dense_10_0 cit_future_dense_50_0 hallwayonehot_final_sparse_15_0
cheese_final_dense_100_0             cit_future_dense_50_1               hallwayonehot_final_sparse_15_1
cheese_final_dense_100_1             cit_future_dense_50_2               hallwayonehot_final_sparse_15_2
cheese_final_dense_100_2             cit_future_dense_50_3               hallwayonehot_final_sparse_15_3
cheese_final_dense_100_3             cit_future_dense_50_4               hallwayonehot_final_sparse_15_4
cheese_final_dense_100_4             cit_future_dense_np.inf_0           hallwayonehot_final_sparse_20_0
cheese_final_dense_10_1              cit_future_dense_np.inf_1           hallwayonehot_final_sparse_20_1
cheese_final_dense_10_2              cit_future_dense_np.inf_2           hallwayonehot_final_sparse_20_2
cheese_final_dense_10_3              cit_future_dense_np.inf_3           hallwayonehot_final_sparse_20_3
cheese_final_dense_10_4              cit_future_dense_np.inf_4           hallwayonehot_final_sparse_20_4
cheese_final_dense_15_0              cit_future_sparse_10_0              hallwayonehot_final_sparse_50_0
cheese_final_dense_15_1              cit_future_sparse_100_0             hallwayonehot_final_sparse_50_1
cheese_final_dense_15_2              cit_future_sparse_100_1             hallwayonehot_final_sparse_50_2
cheese_final_dense_15_3              cit_future_sparse_100_2             hallwayonehot_final_sparse_50_3
cheese_final_dense_15_4              cit_future_sparse_100_3             hallwayonehot_final_sparse_50_4
cheese_final_dense_20_0              cit_future_sparse_100_4             hallwayonehot_final_sparse_np.inf_0
cheese_final_dense_20_1              cit_future_sparse_10_1              hallwayonehot_final_sparse_np.inf_1
cheese_final_dense_20_2              cit_future_sparse_10_2              hallwayonehot_final_sparse_np.inf_2
cheese_final_dense_20_3              cit_future_sparse_10_3              hallwayonehot_final_sparse_np.inf_3
cheese_final_dense_20_4              cit_future_sparse_10_4              hallwayonehot_final_sparse_np.inf_4
cheese_final_dense_50_0              cit_future_sparse_15_0              hallwayonehot_future_dense_10_0
cheese_final_dense_50_1              cit_future_sparse_15_1              hallwayonehot_future_dense_100_0
cheese_final_dense_50_2              cit_future_sparse_15_2              hallwayonehot_future_dense_100_1
cheese_final_dense_50_3              cit_future_sparse_15_3              hallwayonehot_future_dense_100_2
cheese_final_dense_50_4              cit_future_sparse_15_4              hallwayonehot_future_dense_100_3
cheese_final_dense_np.inf_0          cit_future_sparse_20_0              hallwayonehot_future_dense_100_4
cheese_final_dense_np.inf_1          cit_future_sparse_20_1              hallwayonehot_future_dense_10_1
cheese_final_dense_np.inf_2          cit_future_sparse_20_2              hallwayonehot_future_dense_10_2
cheese_final_dense_np.inf_3          cit_future_sparse_20_3              hallwayonehot_future_dense_10_3
cheese_final_dense_np.inf_4          cit_future_sparse_20_4              hallwayonehot_future_dense_10_4
cheese_final_sparse_10_0             cit_future_sparse_50_0              hallwayonehot_future_dense_15_0
cheese_final_sparse_100_0            cit_future_sparse_50_1              hallwayonehot_future_dense_15_1
cheese_final_sparse_100_1            cit_future_sparse_50_2              hallwayonehot_future_dense_15_2
cheese_final_sparse_100_2            cit_future_sparse_50_3              hallwayonehot_future_dense_15_3
cheese_final_sparse_100_3            cit_future_sparse_50_4              hallwayonehot_future_dense_15_4
cheese_final_sparse_100_4            cit_future_sparse_np.inf_0          hallwayonehot_future_dense_20_0
cheese_final_sparse_10_1             cit_future_sparse_np.inf_1          hallwayonehot_future_dense_20_1
cheese_final_sparse_10_2             cit_future_sparse_np.inf_2          hallwayonehot_future_dense_20_2
cheese_final_sparse_10_3             cit_future_sparse_np.inf_3          hallwayonehot_future_dense_20_3
cheese_final_sparse_10_4             cit_future_sparse_np.inf_4          hallwayonehot_future_dense_20_4
cheese_final_sparse_15_0             citonehot_final_dense_10_0          hallwayonehot_future_dense_50_0
cheese_final_sparse_15_1             citonehot_final_dense_100_0         hallwayonehot_future_dense_50_1
cheese_final_sparse_15_2             citonehot_final_dense_100_1         hallwayonehot_future_dense_50_2
cheese_final_sparse_15_3             citonehot_final_dense_100_2         hallwayonehot_future_dense_50_3
cheese_final_sparse_15_4             citonehot_final_dense_100_3         hallwayonehot_future_dense_50_4
cheese_final_sparse_20_0             citonehot_final_dense_100_4         hallwayonehot_future_dense_np.inf_0
cheese_final_sparse_20_1             citonehot_final_dense_10_1          hallwayonehot_future_dense_np.inf_1
cheese_final_sparse_20_2             citonehot_final_dense_10_2          hallwayonehot_future_dense_np.inf_2
cheese_final_sparse_20_3             citonehot_final_dense_10_3          hallwayonehot_future_dense_np.inf_3
cheese_final_sparse_20_4             citonehot_final_dense_10_4          hallwayonehot_future_dense_np.inf_4
cheese_final_sparse_50_0             citonehot_final_dense_15_0          hallwayonehot_future_sparse_10_0
cheese_final_sparse_50_1             citonehot_final_dense_15_1          hallwayonehot_future_sparse_100_0
cheese_final_sparse_50_2             citonehot_final_dense_15_2          hallwayonehot_future_sparse_100_1
cheese_final_sparse_50_3             citonehot_final_dense_15_3          hallwayonehot_future_sparse_100_2
cheese_final_sparse_50_4             citonehot_final_dense_15_4          hallwayonehot_future_sparse_100_3
cheese_final_sparse_np.inf_0         citonehot_final_dense_20_0          hallwayonehot_future_sparse_100_4
cheese_final_sparse_np.inf_1         citonehot_final_dense_20_1          hallwayonehot_future_sparse_10_1
cheese_final_sparse_np.inf_2         citonehot_final_dense_20_2          hallwayonehot_future_sparse_10_2
cheese_final_sparse_np.inf_3         citonehot_final_dense_20_3          hallwayonehot_future_sparse_10_3
cheese_final_sparse_np.inf_4         citonehot_final_dense_20_4          hallwayonehot_future_sparse_10_4
cheese_future_dense_10_0             citonehot_final_dense_50_0          hallwayonehot_future_sparse_15_0
cheese_future_dense_100_0            citonehot_final_dense_50_1          hallwayonehot_future_sparse_15_1
cheese_future_dense_100_1            citonehot_final_dense_50_2          hallwayonehot_future_sparse_15_2
cheese_future_dense_100_2            citonehot_final_dense_50_3          hallwayonehot_future_sparse_15_3
cheese_future_dense_100_3            citonehot_final_dense_50_4          hallwayonehot_future_sparse_15_4
cheese_future_dense_100_4            citonehot_final_dense_np.inf_0      hallwayonehot_future_sparse_20_0
cheese_future_dense_10_1             citonehot_final_dense_np.inf_1      hallwayonehot_future_sparse_20_1
cheese_future_dense_10_2             citonehot_final_dense_np.inf_2      hallwayonehot_future_sparse_20_2
cheese_future_dense_10_3             citonehot_final_dense_np.inf_3      hallwayonehot_future_sparse_20_3
cheese_future_dense_10_4             citonehot_final_dense_np.inf_4      hallwayonehot_future_sparse_20_4
cheese_future_dense_15_0             citonehot_final_sparse_10_0         hallwayonehot_future_sparse_50_0
cheese_future_dense_15_1             citonehot_final_sparse_100_0        hallwayonehot_future_sparse_50_1
cheese_future_dense_15_2             citonehot_final_sparse_100_1        hallwayonehot_future_sparse_50_2
cheese_future_dense_15_3             citonehot_final_sparse_100_2        hallwayonehot_future_sparse_50_3
cheese_future_dense_15_4             citonehot_final_sparse_100_3        hallwayonehot_future_sparse_50_4
cheese_future_dense_20_0             citonehot_final_sparse_100_4        hallwayonehot_future_sparse_np.inf_0
cheese_future_dense_20_1             citonehot_final_sparse_10_1         hallwayonehot_future_sparse_np.inf_1
cheese_future_dense_20_2             citonehot_final_sparse_10_2         hallwayonehot_future_sparse_np.inf_2
cheese_future_dense_20_3             citonehot_final_sparse_10_3         hallwayonehot_future_sparse_np.inf_3
cheese_future_dense_20_4             citonehot_final_sparse_10_4         hallwayonehot_future_sparse_np.inf_4
cheese_future_dense_50_0             citonehot_final_sparse_15_0         mit_final_dense_10_0
cheese_future_dense_50_1             citonehot_final_sparse_15_1         mit_final_dense_100_0
cheese_future_dense_50_2             citonehot_final_sparse_15_2         mit_final_dense_100_1
cheese_future_dense_50_3             citonehot_final_sparse_15_3         mit_final_dense_100_2
cheese_future_dense_50_4             citonehot_final_sparse_15_4         mit_final_dense_100_3
cheese_future_dense_np.inf_0         citonehot_final_sparse_20_0         mit_final_dense_100_4
cheese_future_dense_np.inf_1         citonehot_final_sparse_20_1         mit_final_dense_10_1
cheese_future_dense_np.inf_2         citonehot_final_sparse_20_2         mit_final_dense_10_2
cheese_future_dense_np.inf_3         citonehot_final_sparse_20_3         mit_final_dense_10_3
cheese_future_dense_np.inf_4         citonehot_final_sparse_20_4         mit_final_dense_10_4
cheese_future_sparse_10_0            citonehot_final_sparse_50_0         mit_final_dense_15_0
cheese_future_sparse_100_0           citonehot_final_sparse_50_1         mit_final_dense_15_1
cheese_future_sparse_100_1           citonehot_final_sparse_50_2         mit_final_dense_15_2
cheese_future_sparse_100_2           citonehot_final_sparse_50_3         mit_final_dense_15_3
cheese_future_sparse_100_3           citonehot_final_sparse_50_4         mit_final_dense_15_4
cheese_future_sparse_100_4           citonehot_final_sparse_np.inf_0     mit_final_dense_20_0
cheese_future_sparse_10_1            citonehot_final_sparse_np.inf_1     mit_final_dense_20_1
cheese_future_sparse_10_2            citonehot_final_sparse_np.inf_2     mit_final_dense_20_2
cheese_future_sparse_10_3            citonehot_final_sparse_np.inf_3     mit_final_dense_20_3
cheese_future_sparse_10_4            citonehot_final_sparse_np.inf_4     mit_final_dense_20_4
cheese_future_sparse_15_0            citonehot_future_dense_10_0         mit_final_dense_50_0
cheese_future_sparse_15_1            citonehot_future_dense_100_0        mit_final_dense_50_1
cheese_future_sparse_15_2            citonehot_future_dense_100_1        mit_final_dense_50_2
cheese_future_sparse_15_3            citonehot_future_dense_100_2        mit_final_dense_50_3
cheese_future_sparse_15_4            citonehot_future_dense_100_3        mit_final_dense_50_4
cheese_future_sparse_20_0            citonehot_future_dense_100_4        mit_final_dense_np.inf_0
cheese_future_sparse_20_1            citonehot_future_dense_10_1         mit_final_dense_np.inf_1
cheese_future_sparse_20_2            citonehot_future_dense_10_2         mit_final_dense_np.inf_2
cheese_future_sparse_20_3            citonehot_future_dense_10_3         mit_final_dense_np.inf_3
cheese_future_sparse_20_4            citonehot_future_dense_10_4         mit_final_dense_np.inf_4
cheese_future_sparse_50_0            citonehot_future_dense_15_0         mit_final_sparse_10_0
cheese_future_sparse_50_1            citonehot_future_dense_15_1         mit_final_sparse_100_0
cheese_future_sparse_50_2            citonehot_future_dense_15_2         mit_final_sparse_100_1
cheese_future_sparse_50_3            citonehot_future_dense_15_3         mit_final_sparse_100_2
cheese_future_sparse_50_4            citonehot_future_dense_15_4         mit_final_sparse_100_3
cheese_future_sparse_np.inf_0        citonehot_future_dense_20_0         mit_final_sparse_100_4
cheese_future_sparse_np.inf_1        citonehot_future_dense_20_1         mit_final_sparse_10_1
cheese_future_sparse_np.inf_2        citonehot_future_dense_20_2         mit_final_sparse_10_2
cheese_future_sparse_np.inf_3        citonehot_future_dense_20_3         mit_final_sparse_10_3
cheese_future_sparse_np.inf_4        citonehot_future_dense_20_4         mit_final_sparse_10_4
cheeseonehot_final_dense_10_0        citonehot_future_dense_50_0         mit_final_sparse_15_0
cheeseonehot_final_dense_100_0       citonehot_future_dense_50_1         mit_final_sparse_15_1
cheeseonehot_final_dense_100_1       citonehot_future_dense_50_2         mit_final_sparse_15_2
cheeseonehot_final_dense_100_2       citonehot_future_dense_50_3         mit_final_sparse_15_3
cheeseonehot_final_dense_100_3       citonehot_future_dense_50_4         mit_final_sparse_15_4
cheeseonehot_final_dense_100_4       citonehot_future_dense_np.inf_0     mit_final_sparse_20_0
cheeseonehot_final_dense_10_1        citonehot_future_dense_np.inf_1     mit_final_sparse_20_1
cheeseonehot_final_dense_10_2        citonehot_future_dense_np.inf_2     mit_final_sparse_20_2
cheeseonehot_final_dense_10_3        citonehot_future_dense_np.inf_3     mit_final_sparse_20_3
cheeseonehot_final_dense_10_4        citonehot_future_dense_np.inf_4     mit_final_sparse_20_4
cheeseonehot_final_dense_15_0        citonehot_future_sparse_10_0        mit_final_sparse_50_0
cheeseonehot_final_dense_15_1        citonehot_future_sparse_100_0       mit_final_sparse_50_1
cheeseonehot_final_dense_15_2        citonehot_future_sparse_100_1       mit_final_sparse_50_2
cheeseonehot_final_dense_15_3        citonehot_future_sparse_100_2       mit_final_sparse_50_3
cheeseonehot_final_dense_15_4        citonehot_future_sparse_100_3       mit_final_sparse_50_4
cheeseonehot_final_dense_20_0        citonehot_future_sparse_100_4       mit_final_sparse_np.inf_0
cheeseonehot_final_dense_20_1        citonehot_future_sparse_10_1        mit_final_sparse_np.inf_1
cheeseonehot_final_dense_20_2        citonehot_future_sparse_10_2        mit_final_sparse_np.inf_2
cheeseonehot_final_dense_20_3        citonehot_future_sparse_10_3        mit_final_sparse_np.inf_3
cheeseonehot_final_dense_20_4        citonehot_future_sparse_10_4        mit_final_sparse_np.inf_4
cheeseonehot_final_dense_50_0        citonehot_future_sparse_15_0        mit_future_dense_10_0
cheeseonehot_final_dense_50_1        citonehot_future_sparse_15_1        mit_future_dense_100_0
cheeseonehot_final_dense_50_2        citonehot_future_sparse_15_2        mit_future_dense_100_1
cheeseonehot_final_dense_50_3        citonehot_future_sparse_15_3        mit_future_dense_100_2
cheeseonehot_final_dense_50_4        citonehot_future_sparse_15_4        mit_future_dense_100_3
cheeseonehot_final_dense_np.inf_0    citonehot_future_sparse_20_0        mit_future_dense_100_4
cheeseonehot_final_dense_np.inf_1    citonehot_future_sparse_20_1        mit_future_dense_10_1
cheeseonehot_final_dense_np.inf_2    citonehot_future_sparse_20_2        mit_future_dense_10_2
cheeseonehot_final_dense_np.inf_3    citonehot_future_sparse_20_3        mit_future_dense_10_3
cheeseonehot_final_dense_np.inf_4    citonehot_future_sparse_20_4        mit_future_dense_10_4
cheeseonehot_final_sparse_10_0       citonehot_future_sparse_50_0        mit_future_dense_15_0
cheeseonehot_final_sparse_100_0      citonehot_future_sparse_50_1        mit_future_dense_15_1
cheeseonehot_final_sparse_100_1      citonehot_future_sparse_50_2        mit_future_dense_15_2
cheeseonehot_final_sparse_100_2      citonehot_future_sparse_50_3        mit_future_dense_15_3
cheeseonehot_final_sparse_100_3      citonehot_future_sparse_50_4        mit_future_dense_15_4
cheeseonehot_final_sparse_100_4      citonehot_future_sparse_np.inf_0    mit_future_dense_20_0
cheeseonehot_final_sparse_10_1       citonehot_future_sparse_np.inf_1    mit_future_dense_20_1
cheeseonehot_final_sparse_10_2       citonehot_future_sparse_np.inf_2    mit_future_dense_20_2
cheeseonehot_final_sparse_10_3       citonehot_future_sparse_np.inf_3    mit_future_dense_20_3
cheeseonehot_final_sparse_10_4       citonehot_future_sparse_np.inf_4    mit_future_dense_20_4
cheeseonehot_final_sparse_15_0       hallway_final_dense_10_0            mit_future_dense_50_0
cheeseonehot_final_sparse_15_1       hallway_final_dense_100_0           mit_future_dense_50_1
cheeseonehot_final_sparse_15_2       hallway_final_dense_100_1           mit_future_dense_50_2
cheeseonehot_final_sparse_15_3       hallway_final_dense_100_2           mit_future_dense_50_3
cheeseonehot_final_sparse_15_4       hallway_final_dense_100_3           mit_future_dense_50_4
cheeseonehot_final_sparse_20_0       hallway_final_dense_100_4           mit_future_dense_np.inf_0
cheeseonehot_final_sparse_20_1       hallway_final_dense_10_1            mit_future_dense_np.inf_1
cheeseonehot_final_sparse_20_2       hallway_final_dense_10_2            mit_future_dense_np.inf_2
cheeseonehot_final_sparse_20_3       hallway_final_dense_10_3            mit_future_dense_np.inf_3
cheeseonehot_final_sparse_20_4       hallway_final_dense_10_4            mit_future_dense_np.inf_4
cheeseonehot_final_sparse_50_0       hallway_final_dense_15_0            mit_future_sparse_10_0
cheeseonehot_final_sparse_50_1       hallway_final_dense_15_1            mit_future_sparse_100_0
cheeseonehot_final_sparse_50_2       hallway_final_dense_15_2            mit_future_sparse_100_1
cheeseonehot_final_sparse_50_3       hallway_final_dense_15_3            mit_future_sparse_100_2
cheeseonehot_final_sparse_50_4       hallway_final_dense_15_4            mit_future_sparse_100_3
cheeseonehot_final_sparse_np.inf_0   hallway_final_dense_20_0            mit_future_sparse_100_4
cheeseonehot_final_sparse_np.inf_1   hallway_final_dense_20_1            mit_future_sparse_10_1
cheeseonehot_final_sparse_np.inf_2   hallway_final_dense_20_2            mit_future_sparse_10_2
cheeseonehot_final_sparse_np.inf_3   hallway_final_dense_20_3            mit_future_sparse_10_3
cheeseonehot_final_sparse_np.inf_4   hallway_final_dense_20_4            mit_future_sparse_10_4
cheeseonehot_future_dense_10_0       hallway_final_dense_50_0            mit_future_sparse_15_0
cheeseonehot_future_dense_100_0      hallway_final_dense_50_1            mit_future_sparse_15_1
cheeseonehot_future_dense_100_1      hallway_final_dense_50_2            mit_future_sparse_15_2
cheeseonehot_future_dense_100_2      hallway_final_dense_50_3            mit_future_sparse_15_3
cheeseonehot_future_dense_100_3      hallway_final_dense_50_4            mit_future_sparse_15_4
cheeseonehot_future_dense_100_4      hallway_final_dense_np.inf_0        mit_future_sparse_20_0
cheeseonehot_future_dense_10_1       hallway_final_dense_np.inf_1        mit_future_sparse_20_1
cheeseonehot_future_dense_10_2       hallway_final_dense_np.inf_2        mit_future_sparse_20_2
cheeseonehot_future_dense_10_3       hallway_final_dense_np.inf_3        mit_future_sparse_20_3
cheeseonehot_future_dense_10_4       hallway_final_dense_np.inf_4        mit_future_sparse_20_4
cheeseonehot_future_dense_15_0       hallway_final_sparse_10_0           mit_future_sparse_50_0
cheeseonehot_future_dense_15_1       hallway_final_sparse_100_0          mit_future_sparse_50_1
cheeseonehot_future_dense_15_2       hallway_final_sparse_100_1          mit_future_sparse_50_2
cheeseonehot_future_dense_15_3       hallway_final_sparse_100_2          mit_future_sparse_50_3
cheeseonehot_future_dense_15_4       hallway_final_sparse_100_3          mit_future_sparse_50_4
cheeseonehot_future_dense_20_0       hallway_final_sparse_100_4          mit_future_sparse_np.inf_0
cheeseonehot_future_dense_20_1       hallway_final_sparse_10_1           mit_future_sparse_np.inf_1
cheeseonehot_future_dense_20_2       hallway_final_sparse_10_2           mit_future_sparse_np.inf_2
cheeseonehot_future_dense_20_3       hallway_final_sparse_10_3           mit_future_sparse_np.inf_3
cheeseonehot_future_dense_20_4       hallway_final_sparse_10_4           mit_future_sparse_np.inf_4
cheeseonehot_future_dense_50_0       hallway_final_sparse_15_0           mitonehot_final_dense_10_0
cheeseonehot_future_dense_50_1       hallway_final_sparse_15_1           mitonehot_final_dense_100_0
cheeseonehot_future_dense_50_2       hallway_final_sparse_15_2           mitonehot_final_dense_100_1
cheeseonehot_future_dense_50_3       hallway_final_sparse_15_3           mitonehot_final_dense_100_2
cheeseonehot_future_dense_50_4       hallway_final_sparse_15_4           mitonehot_final_dense_100_3
cheeseonehot_future_dense_np.inf_0   hallway_final_sparse_20_0           mitonehot_final_dense_100_4
cheeseonehot_future_dense_np.inf_1   hallway_final_sparse_20_1           mitonehot_final_dense_10_1
cheeseonehot_future_dense_np.inf_2   hallway_final_sparse_20_2           mitonehot_final_dense_10_2
cheeseonehot_future_dense_np.inf_3   hallway_final_sparse_20_3           mitonehot_final_dense_10_3
cheeseonehot_future_dense_np.inf_4   hallway_final_sparse_20_4           mitonehot_final_dense_10_4
cheeseonehot_future_sparse_10_0      hallway_final_sparse_50_0           mitonehot_final_dense_15_0
cheeseonehot_future_sparse_100_0     hallway_final_sparse_50_1           mitonehot_final_dense_15_1
cheeseonehot_future_sparse_100_1     hallway_final_sparse_50_2           mitonehot_final_dense_15_2
cheeseonehot_future_sparse_100_2     hallway_final_sparse_50_3           mitonehot_final_dense_15_3
cheeseonehot_future_sparse_100_3     hallway_final_sparse_50_4           mitonehot_final_dense_15_4
cheeseonehot_future_sparse_100_4     hallway_final_sparse_np.inf_0       mitonehot_final_dense_20_0
cheeseonehot_future_sparse_10_1      hallway_final_sparse_np.inf_1       mitonehot_final_dense_20_1
cheeseonehot_future_sparse_10_2      hallway_final_sparse_np.inf_2       mitonehot_final_dense_20_2
cheeseonehot_future_sparse_10_3      hallway_final_sparse_np.inf_3       mitonehot_final_dense_20_3
cheeseonehot_future_sparse_10_4      hallway_final_sparse_np.inf_4       mitonehot_final_dense_20_4
cheeseonehot_future_sparse_15_0      hallway_future_dense_10_0           mitonehot_final_dense_50_0
cheeseonehot_future_sparse_15_1      hallway_future_dense_100_0          mitonehot_final_dense_50_1
cheeseonehot_future_sparse_15_2      hallway_future_dense_100_1          mitonehot_final_dense_50_2
cheeseonehot_future_sparse_15_3      hallway_future_dense_100_2          mitonehot_final_dense_50_3
cheeseonehot_future_sparse_15_4      hallway_future_dense_100_3          mitonehot_final_dense_50_4
cheeseonehot_future_sparse_20_0      hallway_future_dense_100_4          mitonehot_final_dense_np.inf_0
cheeseonehot_future_sparse_20_1      hallway_future_dense_10_1           mitonehot_final_dense_np.inf_1
cheeseonehot_future_sparse_20_2      hallway_future_dense_10_2           mitonehot_final_dense_np.inf_2
cheeseonehot_future_sparse_20_3      hallway_future_dense_10_3           mitonehot_final_dense_np.inf_3
cheeseonehot_future_sparse_20_4      hallway_future_dense_10_4           mitonehot_final_dense_np.inf_4
cheeseonehot_future_sparse_50_0      hallway_future_dense_15_0           mitonehot_final_sparse_10_0
cheeseonehot_future_sparse_50_1      hallway_future_dense_15_1           mitonehot_final_sparse_100_0
cheeseonehot_future_sparse_50_2      hallway_future_dense_15_2           mitonehot_final_sparse_100_1
cheeseonehot_future_sparse_50_3      hallway_future_dense_15_3           mitonehot_final_sparse_100_2
cheeseonehot_future_sparse_50_4      hallway_future_dense_15_4           mitonehot_final_sparse_100_3
cheeseonehot_future_sparse_np.inf_0  hallway_future_dense_20_0           mitonehot_final_sparse_100_4
cheeseonehot_future_sparse_np.inf_1  hallway_future_dense_20_1           mitonehot_final_sparse_10_1
cheeseonehot_future_sparse_np.inf_2  hallway_future_dense_20_2           mitonehot_final_sparse_10_2
cheeseonehot_future_sparse_np.inf_3  hallway_future_dense_20_3           mitonehot_final_sparse_10_3
cheeseonehot_future_sparse_np.inf_4  hallway_future_dense_20_4           mitonehot_final_sparse_10_4
cit_final_dense_10_0                 hallway_future_dense_50_0           mitonehot_final_sparse_15_0
cit_final_dense_100_0                hallway_future_dense_50_1           mitonehot_final_sparse_15_1
cit_final_dense_100_1                hallway_future_dense_50_2           mitonehot_final_sparse_15_2
cit_final_dense_100_2                hallway_future_dense_50_3           mitonehot_final_sparse_15_3
cit_final_dense_100_3                hallway_future_dense_50_4           mitonehot_final_sparse_15_4
cit_final_dense_100_4                hallway_future_dense_np.inf_0       mitonehot_final_sparse_20_0
cit_final_dense_10_1                 hallway_future_dense_np.inf_1       mitonehot_final_sparse_20_1
cit_final_dense_10_2                 hallway_future_dense_np.inf_2       mitonehot_final_sparse_20_2
cit_final_dense_10_3                 hallway_future_dense_np.inf_3       mitonehot_final_sparse_20_3
cit_final_dense_10_4                 hallway_future_dense_np.inf_4       mitonehot_final_sparse_20_4
cit_final_dense_15_0                 hallway_future_sparse_10_0          mitonehot_final_sparse_50_0
cit_final_dense_15_1                 hallway_future_sparse_100_0         mitonehot_final_sparse_50_1
cit_final_dense_15_2                 hallway_future_sparse_100_1         mitonehot_final_sparse_50_2
cit_final_dense_15_3                 hallway_future_sparse_100_2         mitonehot_final_sparse_50_3
cit_final_dense_15_4                 hallway_future_sparse_100_3         mitonehot_final_sparse_50_4
cit_final_dense_20_0                 hallway_future_sparse_100_4         mitonehot_final_sparse_np.inf_0
cit_final_dense_20_1                 hallway_future_sparse_10_1          mitonehot_final_sparse_np.inf_1
cit_final_dense_20_2                 hallway_future_sparse_10_2          mitonehot_final_sparse_np.inf_2
cit_final_dense_20_3                 hallway_future_sparse_10_3          mitonehot_final_sparse_np.inf_3
cit_final_dense_20_4                 hallway_future_sparse_10_4          mitonehot_final_sparse_np.inf_4
cit_final_dense_50_0                 hallway_future_sparse_15_0          mitonehot_future_dense_10_0
cit_final_dense_50_1                 hallway_future_sparse_15_1          mitonehot_future_dense_100_0
cit_final_dense_50_2                 hallway_future_sparse_15_2          mitonehot_future_dense_100_1
cit_final_dense_50_3                 hallway_future_sparse_15_3          mitonehot_future_dense_100_2
cit_final_dense_50_4                 hallway_future_sparse_15_4          mitonehot_future_dense_100_3
cit_final_dense_np.inf_0             hallway_future_sparse_20_0          mitonehot_future_dense_100_4
cit_final_dense_np.inf_1             hallway_future_sparse_20_1          mitonehot_future_dense_10_1
cit_final_dense_np.inf_2             hallway_future_sparse_20_2          mitonehot_future_dense_10_2
cit_final_dense_np.inf_3             hallway_future_sparse_20_3          mitonehot_future_dense_10_3
cit_final_dense_np.inf_4             hallway_future_sparse_20_4          mitonehot_future_dense_10_4
cit_final_sparse_10_0                hallway_future_sparse_50_0          mitonehot_future_dense_15_0
cit_final_sparse_100_0               hallway_future_sparse_50_1          mitonehot_future_dense_15_1
cit_final_sparse_100_1               hallway_future_sparse_50_2          mitonehot_future_dense_15_2
cit_final_sparse_100_2               hallway_future_sparse_50_3          mitonehot_future_dense_15_3
cit_final_sparse_100_3               hallway_future_sparse_50_4          mitonehot_future_dense_15_4
cit_final_sparse_100_4               hallway_future_sparse_np.inf_0      mitonehot_future_dense_20_0
cit_final_sparse_10_1                hallway_future_sparse_np.inf_1      mitonehot_future_dense_20_1
cit_final_sparse_10_2                hallway_future_sparse_np.inf_2      mitonehot_future_dense_20_2
cit_final_sparse_10_3                hallway_future_sparse_np.inf_3      mitonehot_future_dense_20_3
cit_final_sparse_10_4                hallway_future_sparse_np.inf_4      mitonehot_future_dense_20_4
cit_final_sparse_15_0                hallwayonehot_final_dense_10_0      mitonehot_future_dense_50_0
cit_final_sparse_15_1                hallwayonehot_final_dense_100_0     mitonehot_future_dense_50_1
cit_final_sparse_15_2                hallwayonehot_final_dense_100_1     mitonehot_future_dense_50_2
cit_final_sparse_15_3                hallwayonehot_final_dense_100_2     mitonehot_future_dense_50_3
cit_final_sparse_15_4                hallwayonehot_final_dense_100_3     mitonehot_future_dense_50_4
cit_final_sparse_20_0                hallwayonehot_final_dense_100_4     mitonehot_future_dense_np.inf_0
cit_final_sparse_20_1                hallwayonehot_final_dense_10_1      mitonehot_future_dense_np.inf_1
cit_final_sparse_20_2                hallwayonehot_final_dense_10_2      mitonehot_future_dense_np.inf_2
cit_final_sparse_20_3                hallwayonehot_final_dense_10_3      mitonehot_future_dense_np.inf_3
cit_final_sparse_20_4                hallwayonehot_final_dense_10_4      mitonehot_future_dense_np.inf_4
cit_final_sparse_50_0                hallwayonehot_final_dense_15_0      mitonehot_future_sparse_10_0
cit_final_sparse_50_1                hallwayonehot_final_dense_15_1      mitonehot_future_sparse_100_0
cit_final_sparse_50_2                hallwayonehot_final_dense_15_2      mitonehot_future_sparse_100_1
cit_final_sparse_50_3                hallwayonehot_final_dense_15_3      mitonehot_future_sparse_100_2
cit_final_sparse_50_4                hallwayonehot_final_dense_15_4      mitonehot_future_sparse_100_3
cit_final_sparse_np.inf_0            hallwayonehot_final_dense_20_0      mitonehot_future_sparse_100_4
cit_final_sparse_np.inf_1            hallwayonehot_final_dense_20_1      mitonehot_future_sparse_10_1
cit_final_sparse_np.inf_2            hallwayonehot_final_dense_20_2      mitonehot_future_sparse_10_2
cit_final_sparse_np.inf_3            hallwayonehot_final_dense_20_3      mitonehot_future_sparse_10_3
cit_final_sparse_np.inf_4            hallwayonehot_final_dense_20_4      mitonehot_future_sparse_10_4
cit_future_dense_10_0                hallwayonehot_final_dense_50_0      mitonehot_future_sparse_15_0
cit_future_dense_100_0               hallwayonehot_final_dense_50_1      mitonehot_future_sparse_15_1
cit_future_dense_100_1               hallwayonehot_final_dense_50_2      mitonehot_future_sparse_15_2
cit_future_dense_100_2               hallwayonehot_final_dense_50_3      mitonehot_future_sparse_15_3
cit_future_dense_100_3               hallwayonehot_final_dense_50_4      mitonehot_future_sparse_15_4
cit_future_dense_100_4               hallwayonehot_final_dense_np.inf_0  mitonehot_future_sparse_20_0
cit_future_dense_10_1                hallwayonehot_final_dense_np.inf_1  mitonehot_future_sparse_20_1
cit_future_dense_10_2                hallwayonehot_final_dense_np.inf_2  mitonehot_future_sparse_20_2
cit_future_dense_10_3                hallwayonehot_final_dense_np.inf_3  mitonehot_future_sparse_20_3
cit_future_dense_10_4                hallwayonehot_final_dense_np.inf_4  mitonehot_future_sparse_20_4
cit_future_dense_15_0                hallwayonehot_final_sparse_10_0     mitonehot_future_sparse_50_0
cit_future_dense_15_1                hallwayonehot_final_sparse_100_0    mitonehot_future_sparse_50_1
cit_future_dense_15_2                hallwayonehot_final_sparse_100_1    mitonehot_future_sparse_50_2
cit_future_dense_15_3                hallwayonehot_final_sparse_100_2    mitonehot_future_sparse_50_3
cit_future_dense_15_4                hallwayonehot_final_sparse_100_3    mitonehot_future_sparse_50_4
cit_future_dense_20_0                hallwayonehot_final_sparse_100_4    mitonehot_future_sparse_np.inf_0
cit_future_dense_20_1                hallwayonehot_final_sparse_10_1     mitonehot_future_sparse_np.inf_1
cit_future_dense_20_2                hallwayonehot_final_sparse_10_2     mitonehot_future_sparse_np.inf_2
cit_future_dense_20_3                hallwayonehot_final_sparse_10_3     mitonehot_future_sparse_np.inf_3
cit_future_dense_20_4                hallwayonehot_final_sparse_10_4     mitonehot_future_sparse_np.inf_4}

#set dir_list {cheese_final_dense_0 cheeseonehot_final_sparse_2 cit_future_dense_4 hallway_final_dense_1 hallwayonehot_final_sparse_3 mit_future_sparse_0 cheese_final_dense_1 cheeseonehot_final_sparse_3 cit_future_sparse_0 hallway_final_dense_2 hallwayonehot_final_sparse_4 mit_future_sparse_1 cheese_final_dense_2 cheeseonehot_final_sparse_4 cit_future_sparse_1 hallway_final_dense_3 hallwayonehot_future_dense_0 mit_future_sparse_2 cheese_final_dense_3 cheeseonehot_future_dense_0 cit_future_sparse_2 hallway_final_dense_4 hallwayonehot_future_dense_1 mit_future_sparse_3 cheese_final_dense_4 cheeseonehot_future_dense_1 cit_future_sparse_3 hallway_final_sparse_0 hallwayonehot_future_dense_2 mit_future_sparse_4 cheese_final_sparse_0 cheeseonehot_future_dense_2 cit_future_sparse_4 hallway_final_sparse_1 hallwayonehot_future_dense_3 mitonehot_final_dense_0 cheese_final_sparse_1 cheeseonehot_future_dense_3 citonehot_final_dense_0 hallway_final_sparse_2 hallwayonehot_future_dense_4 mitonehot_final_dense_1 cheese_final_sparse_2 cheeseonehot_future_dense_4 citonehot_final_dense_1 hallway_final_sparse_3 hallwayonehot_future_sparse_0 mitonehot_final_dense_2 cheese_final_sparse_3 cheeseonehot_future_sparse_0 citonehot_final_dense_2 hallway_final_sparse_4 hallwayonehot_future_sparse_1 mitonehot_final_dense_3 cheese_final_sparse_4 cheeseonehot_future_sparse_1 citonehot_final_dense_3 hallway_future_dense_0 hallwayonehot_future_sparse_2 mitonehot_final_dense_4 cheese_future_dense_0 cheeseonehot_future_sparse_2 citonehot_final_dense_4 hallway_future_dense_1 hallwayonehot_future_sparse_3 mitonehot_final_sparse_0 cheese_future_dense_1 cheeseonehot_future_sparse_3 citonehot_final_sparse_0 hallway_future_dense_2 hallwayonehot_future_sparse_4 mitonehot_final_sparse_1 cheese_future_dense_2 cheeseonehot_future_sparse_4 citonehot_final_sparse_1 hallway_future_dense_3 mit_final_dense_0 mitonehot_final_sparse_2 cheese_future_dense_3 cit_final_dense_0 citonehot_final_sparse_2 hallway_future_dense_4 mit_final_dense_1 mitonehot_final_sparse_3 cheese_future_dense_4 cit_final_dense_1 citonehot_final_sparse_3 hallway_future_sparse_0 mit_final_dense_2 mitonehot_final_sparse_4 cheese_future_sparse_0 cit_final_dense_2 citonehot_final_sparse_4 hallway_future_sparse_1 mit_final_dense_3 mitonehot_future_dense_0 cheese_future_sparse_1 cit_final_dense_3 citonehot_future_dense_0 hallway_future_sparse_2 mit_final_dense_4 mitonehot_future_dense_1 cheese_future_sparse_2 cit_final_dense_4 citonehot_future_dense_1 hallway_future_sparse_3 mit_final_sparse_0 mitonehot_future_dense_2 cheese_future_sparse_3 cit_final_sparse_0 citonehot_future_dense_2 hallway_future_sparse_4 mit_final_sparse_1 mitonehot_future_dense_3 cheese_future_sparse_4 cit_final_sparse_1 citonehot_future_dense_3 hallwayonehot_final_dense_0 mit_final_sparse_2 mitonehot_future_dense_4 cheeseonehot_final_dense_0 cit_final_sparse_2 citonehot_future_dense_4 hallwayonehot_final_dense_1 mit_final_sparse_3 mitonehot_future_sparse_0 cheeseonehot_final_dense_1 cit_final_sparse_3 citonehot_future_sparse_0 hallwayonehot_final_dense_2 mit_final_sparse_4 mitonehot_future_sparse_1 cheeseonehot_final_dense_2 cit_final_sparse_4 citonehot_future_sparse_1 hallwayonehot_final_dense_3 mit_future_dense_0 mitonehot_future_sparse_2 cheeseonehot_final_dense_3 cit_future_dense_0 citonehot_future_sparse_2 hallwayonehot_final_dense_4 mit_future_dense_1 mitonehot_future_sparse_3 cheeseonehot_final_dense_4 cit_future_dense_1 citonehot_future_sparse_3 hallwayonehot_final_sparse_0 mit_future_dense_2 mitonehot_future_sparse_4 cheeseonehot_final_sparse_0 cit_future_dense_2 citonehot_future_sparse_4 hallwayonehot_final_sparse_1 mit_future_dense_3 cheeseonehot_final_sparse_1 cit_future_dense_3 hallway_final_dense_0 hallwayonehot_final_sparse_2 mit_future_dense_4}

set password [lindex $argv 0]

foreach dir $dir_list {
    spawn scp -r kevin@10.200.205.233:/home/kevin/Development/gym-pomdps/logs_32/$dir logs/
    expect "kevin@10.200.205.233's password:"
    send "$password\r";
    send "$password\r";
    send "$password\r";
    interact
}
